import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import AuthModalProvider from "./_components/providers/AuthModalProvider";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "700"], // Adjust the weights as needed
});

export const metadata = {
  title: "ErgoHub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <div className="">
          <Header/>
          {children}
          <AuthModalProvider/>
        </div>
      </body>
    </html>
  );
}
